### ISSUE TITLE
testudo.py doesn't support more than one professor per section

### ISSUE THREAD

**Issue by qiolol** [edsu/testudo#4]
For a class like [Fall 2019's MUSC229K](https://app.testudo.umd.edu/soc/search?courseId=MUSC229K&sectionId=&termId=201908&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on), there are two sections, both with the same three professors listed:
```
0101
Andrea Brown, Craig Potter, Ann Kennedy

FC01
Ann Kennedy, Craig Potter, Andrea Brown
```
The HTML for section 0101, for example, looks like:
```
<span class="section-instructors">
    <span class="section-instructor">Ann Kennedy</span>,
    <span class="section-instructor">Craig Potter</span>,
    <span class="section-instructor">Andrea Brown</span>
</span>
```

However, `testudo.py`'s [line 78](https://github.com/edsu/testudo/blob/master/testudo.py#L78) only grabs the first `.section-instructor` div element, resulting in the json object only holding the first of the three instructors of these sections, whichever came first (here, Andrea Brown for 0101 and Ann Kennedy for FC01):

```
  "sections": [
    {
      "id": "0101",
      "instructor": "Andrea Brown,",
      "seats": 30,
      "open-seats": 6,
      "waitlist": 0,
      "days": "Su",
      "start": "7:00pm",
      "end": "9:30pm",
      "building": "TBA",
      "room": ""
    },
    {
      "id": "FC01",
      "instructor": "Ann Kennedy,",
      "seats": 10,
      "open-seats": 8,
      "waitlist": 0,
      "days": "Su",
      "start": "7:00pm",
      "end": "9:30pm",
      "building": "TBA",
      "room": ""
    }
  ],
```

**Comment by edsu** [comment]
Nice catch! I didn't realize there could be more than one instructor per section. I guess the instructors stanza should be a list?

```javascript
{
  "id": "0101",
  "instructors": ["Ann Kennedy", "Andrea Brown", "Craig Potter"],
  "seats": 30,
  "open-seats": 6,
  "waitlist": 0,
  "days": "Su",
  "start": "7:00pm",
  "end": "9:30pm",
  "building": "TBA",
  "room": ""
}
```

```

**Comment by qiolol** [comment]
Ah, yep. : p In that case, `json2csv.py`'s [line 29](https://github.com/edsu/testudo/blob/master/json2csv.py#L29) should be something like:

```Python
profs = set()                                     

for s in course['sections']:                      
    for i in s['instructors']:                    
        profs.add(i)
profs = "; ".join(profs)
```

Or, to keep it a list comprehension,
```Python
profs = "; ".join([i for sec_list in [[i for i in s['instructors']] for s in course['sections']] for i in sec_list])
```

**Comment by edsu** [comment]
I've updated testudo.py and json2csv.py for the new instructors list.

Very nice catch on noticing this. I missed that sections could have multiple instructors, and just from eyeballing the data it looks like they are fairly common!
