### ISSUE TITLE
json2csv.py includes the same professor many times

### ISSUE THREAD

**Issue by qiolol** [edsu/testudo#5]
Consider a class like [Fall 2019's MUSC210](https://app.testudo.umd.edu/soc/search?courseId=MUSC210&sectionId=&termId=201908&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on), with many sections all taught by one professor. 

[Line 29](https://github.com/edsu/testudo/blob/master/json2csv.py#L29)'s list comprehension in `json2csv.py` does no checking of redundant inclusions of names, resulting in the "instructors" field of MUSC210 in the CSV file to be `Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios; Fernando Rios,`.

Replacing that line with
```Python
profs = []

for section in course['sections']:
    if section['instructor'] not in profs:
        profs.append(section['instructor'])
profs = "; ".join(profs)
```
fixes this.

**Comment by edsu** [comment]
Thanks for noticing this!
