### ISSUE TITLE
testudo.py includes hyphens of credit ranges in JSON

### ISSUE THREAD

**Issue by qiolol** [edsu/testudo#6]
A variable credit class like [Spring 2020's DANC698](https://app.testudo.umd.edu/soc/search?courseId=DANC698&sectionId=&termId=202001&_openSectionsOnly=on&creditCompare=&credits=&courseLevelFilter=ALL&instructor=&_facetoface=on&_blended=on&_online=on&courseStartCompare=&courseStartHour=&courseStartMin=&courseStartAM=&courseEndHour=&courseEndMin=&courseEndAM=&teachingCenter=ALL&_classDay1=on&_classDay2=on&_classDay3=on&_classDay4=on&_classDay5=on) reports `Credits: 1 - 3`.

The HTML for this looks like:
```html
<div class="course-credits-group two columns">
    <div>
        <span class="course-info-label">Credits:</span>
        <span class="course-min-credits">1</span> 
        - 
        <span class="course-max-credits">3</span>
    </div>
</div>
```

Although [line 59](https://github.com/edsu/testudo/blob/master/testudo.py#L59) seems to correctly isolate the `course-min-credits` element, which in this case would just be `1`, the credits field for such classes' JSON ends up being:

```json
"credits": "1 -",
```

**Comment by qiolol** [comment]
Actually, this seems fixed on the latest version!

**Comment by edsu** [comment]
Are you sure? I don't remember changing anything related to this...

**Comment by qiolol** [comment]
I assumed you did, although the relevant code in `testudo.py` seemed strangely untouched.

And yet, using the course DANC698 from Fall 2019 (201908), here's a snippet of a JSON file from before:
```json
{
  "id": "DANC698",
  "title": "Independent Study in Dance",
  "credits": "1 -",
  "description": "",
  "grading-method": [
    "Reg",
    "Aud"
  ],
  "sections": [
    {
      "id": "0101",
      "instructor": "Patrik Widrig",
      "seats": 3,
      "open-seats": 3,
      "waitlist": 0,
      "days": "",
      "start": "",
      "end": "",
      "building": "",
      "room": ""
    },
```
Notice the `instructor` field is a plain string.
We have `"credits": "1 -",`.

Here's a snippet of the same JSON, freshly-downloaded:

```json
{
  "id": "DANC698",
  "title": "Independent Study in Dance",
  "credits": "1",
  "description": "",
  "grading-method": [
    "Reg",
    "Aud"
  ],
  "sections": [
    {
      "id": "0101",
      "instructors": [
        "Patrik Widrig"
      ],
      "seats": 3,
      "open-seats": 3,
      "waitlist": 0,
      "days": "",
      "start": "",
      "end": "",
      "building": "",
      "room": ""
    },
```
Notice the new `instructors` field with a list of instructors, per the update.
We now have `"credits": "1",`.

Fixed, somehow. : o
